sudo: false
language: python
# When updating, don't forget tox.ini
# Not supported (yet)
#  - "3.4"
#  - "3.5"
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pep8
# Pylint is broken, not debugging now..
#  - TOXENV=pylint
  - TOXENV=docs
  - TOXENV=cover
  - TOXENV=codacy-coverage-upload TOX_TESTENV_PASSENV=CODACY_PROJECT_TOKEN
install:
  - pip install tox-travis
script: tox
